version: "3.1"
services:
  app:
    image: ecomart 
    container_name: ecomart_php8_2
    build: 
      context: .
      dockerfile: .
    restart: "no"
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ecomart

    command: "php artisan serve --host=0.0.0.0 --port=8000"

   

  db:
    image: mysql:latest
    container_name: mysql_db_ecomart
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data_ecomart:/docker-entrypoint-initdb.d
      - db_data_ecomart:/var/lib/mysql
    networks:
      - ecomart
   
  
  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    restart: "no"
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - ecomart


networks:
  ecomart:
    driver: bridge


volumes:
  db_data_ecomart: